apiVersion: apps/v1
kind: Deployment
metadata:
  name: app2-deployment
  namespace: app2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app2
  template:
    metadata:
      labels:
        app: app2
    spec:
      containers:
      - name: app2
        image: 123456789012.dkr.ecr.us-east-1.amazonaws.com/app2:hotfix-latest
        ports:
        - containerPort: 80
